### ISSUE TITLE
Complete website configuration

### ISSUE THREAD

**Issue by edjeavons** [eighteen73/wp-cli-tools#1]
Some website (not plugin) settings still need to be configured during install, including:

- Language
- Timezone
- Date format
- Disable comments

**Comment by brettsmason** [comment]
A couple of other ones I do on every site:

- Set the permalink structure
- Disable show avatars under Discussion (saves a request)
- Delete the default tagline

I do exactly the same steps/settings on any site so let me know if you need these.

**Comment by edjeavons** [comment]
All done
