### ISSUE TITLE
[Sync] Flush permalinks on successful sync

### ISSUE THREAD

**Issue by brettsmason** [eighteen73/wp-cli-tools#14]
There have been a few issues recently with failed uploads or editor errors which have been down to permalinks needing to be flushed.
I suggest we add `wp rewrite flush` to the sync scripts to hopefully alleviate this.

**Comment by edjeavons** [comment]
I've added a post-sync operation that runs all of the following, just to be extra thorough:

```shell
wp rewrite flush
wp transient delete --all
wp cache flush
```
